// Generated by CoffeeScript 1.6.3
(function() {
  var rack, racksjs,
    _this = this;

  racksjs = require('./racks.js');

  rack = false;

  new racksjs({
    username: process.argv[2],
    apiKey: process.argv[3],
    verbosity: 0,
    cache: false
  }, function(rs) {
    rack = rs;
    rack.datacenter = 'IAD';
    return rack.servers.all(function(servers) {
      var server, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = servers.length; _i < _len; _i++) {
        server = servers[_i];
        _results.push(server.metadata(function(metadata) {
          return console.log(metadata);
        }));
      }
      return _results;
    });
  });

}).call(this);
